apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: web
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 9090
      protocol: TCP

